---
title: "Homework4"
output: html_document
date: "2025-02-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Solutions to homework 4 problems with code chunks and plain text.

#### Question 1
``` {r}
# 1a
x <- 1.1
a <- 2.2
b <- 3.3

z <- x^a^b
print(z)

# 1b
z <- (x^a)^b
print(z)

# 1c
z <- 3*x^3 + 2*x^2 + 1
print(z)
```

#### Question 2
```{r}
# 2a
z <- c(seq(1:8), seq(from=7, to=1, by=-1))
print(z)

# 2b
z <- c(rep(1,1), rep(2,2), rep(3,3), rep(4,4), rep(5,5))
print(z)

# 2c
z <- c(rep(5,1), rep(4,2), rep(3,3), rep(2,4), rep(1,5))
print(z)
```

#### Question 3
```{r}
values <- runif(n=2, min=0, max=10) # Get random values
print(values)
r <- sqrt(values[1]^2 + values[2]^2) # Get r
theta = atan(values[2]/values[1]) # Get theta
polar = c(r,theta) # Create new vector with r and theta
print(polar)
```

#### Question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
# 4a
queue <- c(queue, "serpent")
print(queue)
# 4b
queue <- queue[2:length(queue)]
print(queue)
# 4c
queue <- c("donkey", queue)
print(queue)
# 4d
queue <- queue[-length(queue)]
print(queue)
# 4e
queue <- queue[queue != "owl"]
print(queue)
# 4f
position <- which(queue == 'ant')
queue <- c(queue[1:position-1], "aphid", queue[position:length(queue)])
print(queue)
# 4g
position_aphid <- which(queue == 'aphid')
print(position_aphid)
```

#### Question 5
```{r}
vec <- seq(1,100) # Get vector of integers from 1 to 100
pos <- which(vec%%2 != 0 & vec%%5 != 0 & vec%%7 !=0) # Find indices where the integers are not divisible by 2, 5, or 7 
vec <- vec[pos] # Adjust vec to be only numbers with said pos
print(vec)
```



